apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabniki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabniki
  template:
    metadata:
      labels:
        app: uporabniki
    spec:
      containers:
        - image: rsoskupina50/uporabnikova-shramba-izdelkov:2022-12-04-14-24-07
          name: uporabnikovi
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/auevkfam
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: auevkfam
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: KOOUb0UkwgcslLt66MRP3jL5BIH9C48c
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: uporabniki
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: uporabniki
